hp = {
    "hid_dim": 128,
    "phone_dim": 40,
    "reconstr_weight": 30,
    "n_fft": 1024,
    "n_mels": 128,
    "hop_size": 256,
    "win_size": 1024,
    "epochs": 75,
    "batch_size": 64,
    "corpus_name": "common_voice_jp",
    "learning_rate": 1e-4,
    "phone_set": [
        "I",
        "N",
        "U",
        "a",
        "b",
        "by",
        "ch",
        "cl",
        "d",
        "dy",
        "e",
        "f",
        "g",
        "gy",
        "h",
        "hy",
        "i",
        "j",
        "k",
        "ky",
        "m",
        "my",
        "n",
        "ny",
        "o",
        "p",
        "pau",
        "py",
        "r",
        "ry",
        "s",
        "sh",
        "t",
        "ts",
        "ty",
        "u",
        "v",
        "w",
        "y",
        "z",
    ],
}
